title: SawyerJ.Myers
logo: /assets/img/headshot.png
role: Data Scientist, Software Engineer
education: University of Oklahoma, May 2021

show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
