title: S. Myers
logo: /assets/img/headshot-color.png
role: Data Scientist · Software Engineer · Artist
education: University of Oklahoma, May 2021
degree: Major in Computer Science, Minor in Mathematics
theme: jekyll-theme-minimal
