title: S. Myers
logo: /assets/img/portrait.png
role: Data Scientist · Software Engineer · Artist
education: University of Oklahoma, May 2021
degree: Major in Computer Science, Minor in Mathematics
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
