title: Sawyer J. Myers
logo: /assets/img/portrait.png
role: Data Scientist, Software Engineer
education: University of Oklahoma, May 2021

show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
