title: S.J. Myers
logo: /assets/img/headshot.png
description: Website
theme: jekyll-theme-minimal
show_downloads: false
google_analytics: false
github.is_project_page: false
github.is_user_page: false
content: ???
